name: Integration Tests
on:
  workflow_dispatch:
  push:
permissions:
  id-token: write
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: 'phantomcyber/dev-cicd-tools/github-actions/integration-tests@aws'
        with:
          AWS_ROLE_ARN: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
